service-url: /api/auth

server:
  port: 8085
  shutdown: graceful

coolsms:
  apikey: ${SMS_KEY}
  apisecret: ${SMS_SECRETKEY}
  fromnumber: ${PHONE}

spring:
  token:
    secret: ${SECRET}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    id: ${REDIS_ID}
    pw: ${REDIS_PW}
  application:
    name: auth
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SEVER}
    consumer:
      auto-offset-reset: ${OFFSET_TYPE}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.example
  show-login-endpoint: true

