service-url: /api

server:
  port: 8080
  servlet:
    context-path: ${service-url}

spring:
  token:
    secret: ${SECRET}
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://3.36.196.194:5173'
              - 'http://localhost:5173'
              - 'http://stock-craft.kro.kr'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: basic
          uri: http://localhost:8081
          predicates:
            - Path= ${service-url}/basic/**
          filters:
            - RewritePath=${service-url}/basic/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: mypage
          uri: http://172.31.3.175:8082
          predicates:
            - Path= ${service-url}/my/**
          filters:
            - RewritePath=${service-url}/my/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
            - RewritePath=${service-url}/mypage/(?<path>.*),/$\{path}
        - id: reward
          uri: http://172.31.3.113:8083
          predicates:
            - Path= ${service-url}/reward/**
          filters:
            - RewritePath=${service-url}/reward/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: search
          uri: http://172.31.3.217:8084
          predicates:
            - Path= ${service-url}/search/**
          filters:
            - RewritePath=${service-url}/search/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter
        - id: auth
          uri: http://172.31.3.103:8085
          predicates:
            - Path= ${service-url}/auth/**
          filters:
              - RewritePath=${service-url}/auth/(?<path>.*),/$\{path}
        - id: home
          uri: http://172.31.3.21:8086
          predicates:
            - Path= ${service-url}/home/**
          filters:
            - RewritePath=${service-url}/home/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter




springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  webjars:
    prefix: ${service-url}
  swagger-ui:
    operations-sorter: alpha
    use-root-path: false
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: ${service-url}/basic/v3/api-docs
        name: Basic
      - url: ${service-url}/auth/v3/api-docs
        name: Auth
      - url: ${service-url}/my/v3/api-docs
        name: Mypage
      - url: ${service-url}/reward/v3/api-docs
        name: Reward
      - url: ${service-url}/search/v3/api-docs
        name: Search
      - url: ${service-url}/home/v3/api-docs
        name: Home

