service-url: /api

server:
  port: 8080
  servlet:
    context-path: ${service-url}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: basic
          uri: http://localhost:8081
          predicates:
            - Path= ${service-url}/basic/**
          filters:
            - RewritePath=${service-url}/basic/(?<path>.*),/$\{path}





