service-url: /api

server:
  port: 8080
  servlet:
    context-path: ${service-url}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: basic
          uri: http://localhost:8081
          predicates:
            - Path= ${service-url}/basic/**
          filters:
            - RewritePath=${service-url}/basic/(?<path>.*),/$\{path}
        - id: mypage
          uri: http://localhost:8082
          predicates:
            - Path= ${service-url}/mypage/**
          filters:
            - RewritePath=${service-url}/mypage/(?<path>.*),/$\{path}
        - id: reward
          uri: http://localhost:8083
          predicates:
            - Path= ${service-url}/reward/**
          filters:
            - RewritePath=${service-url}/reward/(?<path>.*),/$\{path}
        - id: auth
          uri: http://localhost:8085
          predicates:
            - Path= ${service-url}/auth/**
          filters:
            - RewritePath=${service-url}/auth/(?<path>.*),/$\{path}


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

  webjars:
    prefix: ${service-url}
  swagger-ui:
    operations-sorter: alpha
    use-root-path: false
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: ${service-url}/basic/v3/api-docs
        name: Basic
      - url: ${service-url}/mypage/v3/api-docs
        name: Mypage
      - url: ${service-url}/reward/v3/api-docs
        name: Reward
      - url: ${service-url}/auth/v3/api-docs
        name: Auth






