service-url: /api/reward

server:
  port: 8083
  shutdown: graceful

spring:
  application:
    name: reward
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.example

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      region:
        static: ${CLOUD_AWS_REGION_STATIC}
      s3:
        bucket: ${CLOUD_AWS_S3_BUCKET}

authorization: ${AUTHORIZATION}
appKey: ${APPKEY}
appSecret: ${APPSECRET}

BOOTSTRAP_SERVERS_CONFIG: ${BOOTSTRAP_SERVERS_CONFIG}